from models.markov._train_markov_model import load_model, generate_text



def random_markov_model(length : int,
                        start_word : str,
                        model_path : str) -> str:
    """
    Uses a random markov model trained off some poetry.
    NOTE: model output is not conditioned off user input.

    Parameters
    ----------
    length : int
        How many words should be in the output.
    start_word : str
        The first word in the response.
        NOTE: this word must belong to the vocabulary.
    model_path : str
        Path to the trained model.
    
    Returns
    -------
    str
        Words in a string.
    """
    # Load model
    loaded_model = load_model(model_path)

    # Generate and print text
    text = generate_text(loaded_model,
                        start_word=start_word,
                        length=length)

    return text


def get_response(text : str,
                 model : str) -> str:
    """
    Produces a text reply to a text input.

    Parameters
    ----------
    text : str
        The input text that the response is conditioned on.
    model : str
        Which model to use. Current models:
            - "echo"
                Repeats back the input text.
            - "random markov"
                Random text from a trained markov model.
    
    Returns
    ------
    str
        The reply generated by the model.
    """
    if model == "echo":
        return text
    
    if model == "random_markov":
        text = random_markov_model(length=30,
                                   start_word="the",
                                   model_path="models/markov/_random_poems_model.pkl")
    
        return text
        
